import { ChakraProvider, Flex } from '@chakra-ui/react';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { container } from 'tsyringe';
import { FileTreeView } from '../components/FileTreeView';
import { UniverseView } from '../components/UniverseView';
import { useAsteroidFiles } from '../hooks/workspace';
import { workspaceServiceToken, WorkspaceService } from '../services/workspace';
import { AsteroidFileItem } from '../types/workspace';

interface PageProps {
  asteroid: AsteroidFileItem<number>[];
}

export const getServerSideProps: GetServerSideProps<PageProps> = async () => {
  const cli = container.resolve<WorkspaceService>(workspaceServiceToken);
  const asteroid = (await cli.service.getAsteroidFiles()).map((it) => ({
    ...it,
    mtime: it.mtime.getTime(),
    birthtime: it.mtime.getTime(),
  }));
  return {
    props: { asteroid },
  };
};

export default function Home({ asteroid }: PageProps) {
  const { setAsteroidFiles } = useAsteroidFiles();
  useEffect(() => {
    setAsteroidFiles(
      asteroid.map((it) => ({
        ...it,
        mtime: new Date(it.mtime),
        birthtime: new Date(it.mtime),
      }))
    );
  }, []);

  return (
      <ChakraProvider>
        <Head>
          <title>Asteroid</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Flex alignItems="stretch" height="100vh">
          <Flex
            as="aside"
            flexBasis={40}
            overflow="auto"
            flexDir="column"
            alignItems="stretch"
          >
            <FileTreeView />
          </Flex>
          <Flex
            as="main"
            flex={1}
            overflow="auto"
            flexDir="column"
            alignItems="stretch"
          >
            <UniverseView />
          </Flex>
        </Flex>
      </ChakraProvider>
  );
}
